# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b990af1a3f19d95d3d76a9b0a3acd3f27fa48d806d54ddad9f6ca2192f448bfb1497cc582cf48568f8740915e4aa0ec97632738076f82fffe3f767f59de6dff8

test:
  secret_key_base: 0234dac99d1a502fc3795aa5baa2231b8afc60ff94d8ea504c375e6fa9f2f253ac8ebfc758a79a1c63c3c48498d34bafa02af433acb65b6f24de0eadfe160da1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
